config/routes.rb
Bowling::Application.routes.draw do
  devise_for :users
  root 'bowling_games#index'
  resources :bowling_games, only: [:show, :index, :new, :create]
  get "/bowling_games/:id/new-comment" => "comments#new"
  post "/bowling_games/:id/create-comment" => "comments#create"

  

end

app/models/bowling_game.rb
# Represents an entire game of bowling.
class BowlingGame < ActiveRecord::Base
  belongs_to :user
  has_many :frames
  has_many :comments
  accepts_nested_attributes_for :frames
  accepts_nested_attributes_for :comments

  scope :with_comments_and_frames, includes(:comments, :frames)
  scope :with_user, ->(user_id) { where(user_id: user_id) }
   
  # Checks if the game has ten frames.
  #
  # @returns True if there are ten frames, numbered 1 through 10.
  def finished?
    sorted_frames = frames.sort {|a,b| a.number <=> b.number}
    sorted_frames.length == 10 && check_frames_one_to_ten(sorted_frames)
  end

  # Score the game by adding up the socres of each individual frame.
  def score_game
    self.score = frames.reduce(0) { |sum, frame| sum + score_frame(frame) } 
  end

  # Score an individual frame.
  #
  # @params frame [Frame] The frame to score.
  def score_frame frame
    if frame.strike?
      frame.first_throw + next_two_throws_after_strike(frame)
    elsif frame.spare?
      frame.first_throw + frame.second_throw + next_throw_after_spare(frame)
    else
      frame.first_throw + frame.second_throw
    end
  end

  private

  # Get the next throw from the frame a spare happened on
  #
  # @params frame [Frame] The current frame in which the spare occured.
  # @returns The value of the next throw after a spare.
  def next_throw_after_spare frame
    if frame.number != 10
      next_frame(frame).first_throw
    else
      frame.third_throw
    end
  end

  # Get the sum of the next two throws from the frame a strike happened on.
  #
  # @params frame [Frame] The current frame in which the strike occured.
  # @returns The sum of the next two throws after a strike.
  def next_two_throws_after_strike frame
    if frame.number != 10
      next_frame = next_frame(frame)
      first_throw = next_frame.first_throw
      second_throw = second_throw_after_strike(next_frame)
    else
      first_throw = frame.second_throw
      second_throw = frame.third_throw
    end
    first_throw + second_throw
  end
  
  # Gets the second throw to add to a strike.
  #
  # @params next_frame [Frame] The next frame after the strike occured.
  # @returns The value of the second throw after a strike.
  def second_throw_after_strike(next_frame)
    if next_frame.strike? && next_frame.number != 10
        secondary_frame = next_frame(next_frame)
        second_throw = secondary_frame.first_throw
    else
      second_throw = next_frame.second_throw
    end
  end

  # Gets the next frame.
  #
  # @params current_frame [Frame] Current frame that is not the last frame.
  # @returns The next frame after the current frame.
  def next_frame(current_frame)
    frames.select{|related_frame| related_frame.number ==  current_frame.number + 1}.first
  end

  # Checks to see if all frames are numbered 1 through 10.
  #
  # @params sorted_frames [Array] A list of all the frames sorted 1 through ten.
  # @returns True if the frames are numbered 1 through 10.
  def check_frames_one_to_ten(sorted_frames)
    has_ten_frames = true
    sorted_frames.zip(1..10).each do |frame_index_pair|
      if frame_index_pair[0].number != frame_index_pair[1]
        has_ten_frames = false
      end
    end
    return has_ten_frames 
  end

end

app/controllers/bowling_games_controller.rb
class BowlingGamesController < ApplicationController
  before_action :authenticate_user!

  # Show a single game
  def show
    @bowling_game = BowlingGame.with_comments_and_frames.with_user(current_user.id).find_by_id(params[:id])
    if !@bowling_game
      redirect_to(bowling_games_path)
    end
  end

  # List all games, frames, comments, and user average
  def index
    @bowling_games = BowlingGame.where(user_id: current_user.id)
    @average_score = current_user.average_score @bowling_games
  end

  # Fill out a form to create a new game with 10 frames
  def new
    @bowling_game = BowlingGame.new
    10.times {@bowling_game.frames.build }
    3.times { @bowling_game.comments.build }
  end

  # Created a new game with the posted params
  def create
    @bowling_game = BowlingGame.new(bowling_game_params)
    @bowling_game.user_id = current_user.id
    if @bowling_game.finished?
      try_score_and_save_game
    else
      render_new_with_error "You did not complete the bowling game."
    end
  end

  private 

  # Attempts to save @bowling_game. Renders an error if not valid.
  def try_score_and_save_game
    if @bowling_game.valid?
      @bowling_game.score_game
      @bowling_game.save
      redirect_to bowling_games_path
    else
      render_new_with_error
    end
  end

  # Renders the new template with an error message.
  #
  # @params error [String] An optional error message to render.
  #   If error is not passed in (or nil), then find the error on the @bowling_game object.
  def render_new_with_error(error = nil)
    unless error
      error = find_error_on_bowling_game
    end
    flash[:error] = error
    render :new
  end

  # Finds the error on the bowling game.
  def find_error_on_bowling_game
    @bowling_game.frames.each do |frame|
      if frame.errors.count > 0
        error = "Frame number #{frame.number} - #{frame.errors.full_messages.first}"
      end
    end
    error = "Errors: " + @bowling_game.errors.full_messages.first unless error
    return error
  end

  def bowling_game_params
    params.require(:bowling_game).permit(:user_id, frames_attributes: [:id, :first_throw, :second_throw, :third_throw, :number], comments_attributes: [:id, :body])
  end
end

app/helpers/bowling_game_helper.rb
module BowlingGameHelper
end

app/views/bowling_games/index.html.erb
<h2>My Games</h2>
<table>
<tr><th>Score</th><th>Created at date</th><th>Comments</th><th></th><th></tr>
<% @bowling_games.each do |bowling_game| %>
	<tr>
	<td><%= bowling_game.score %></td>
	<td><%= bowling_game.created_at %></td>
	<td>
		<% bowling_game.comments.each_with_index do |comment, index| %><%= comment.body %>
			<% if index != bowling_game.comments.length - 1 %>
				, 
			<% end %>
		<% end %>
	</td>
<td><%= link_to "New Comment", "/bowling_games/#{bowling_game.id}/new-comment" %></td>
<td><%= link_to "View Game", bowling_game_path(bowling_game.id) %></td>
	</tr>
	<% end %>
</table>
<% if !@average_score.nan? %><p>Average Score: <%= number_with_precision(@average_score, precision: 2) %></p><% end %>
<%= link_to "New Game", new_bowling_game_path %>

app/views/bowling_games/new.html.erb
<h2>New Game</h2>
<%= form_for @bowling_game do |f| %>
<ul>
	<% frame_number = 1 %>
	<%= f.fields_for :frames do |frame_form| %>
	<li>
	<h3>Frame <%= frame_number %></h3>
	<table class="frame-card">
		<tr><td><label>First Throw: </label></td><td><%= frame_form.number_field :first_throw %></td></tr>
		<tr><td><label>Second Throw: </label></td><td><%= frame_form.number_field :second_throw %></td></tr>
		<% if frame_number == 10 %> 
			<tr><td>Third Throw: </td><td><%= frame_form.number_field :third_throw %></td></tr>
		<% end %>
	</table>
		<%= frame_form.hidden_field :number, value: frame_number %>
		<% frame_number = frame_number + 1 %>
	</li>
	<% end %>
</ul>
<div class="comments">
<%= f.fields_for :comments do |comment_form| %>
	<div class="comment">
		Comment: <%= comment_form.text_area :body %><br/>
	</div>
<% end %>
</div>
<%= f.submit ("Submit") %>
<% end %>

app/views/bowling_games/show.html.erb
<h2>Total score: <%= @bowling_game.score %> </h2>
<% @bowling_game.frames.each do |frame| %>
<div class="frame-view">
	<h3>Frame <%= frame.number %></h3>
	<table class="score-card">
		<tr><td>First Throw:</td><td> <%= frame.first_throw %> </td></tr>
	<tr><td>Second Throw: </td><td><%= frame.second_throw %> </td></tr>
	<% if frame.number == 10 && frame.third_throw %>
		<tr><td> Third Throw: </td><td> <%= frame.third_throw %></td></tr>
	<% end %>
</table>
</div>
<% end %>
<div class="comments">
<h3>Comments</h3>
<% @bowling_game.comments.each do |comment| %>
	<p><%= comment.body %></p>
<% end %>
</div>